# Generated by Django 2.2.3 on 2019-08-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bovino',
            fields=[
                ('id_bovino', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_bovino', models.IntegerField()),
                ('identidad_ica', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('nombre_madre', models.CharField(max_length=45)),
                ('nombre_padre', models.CharField(max_length=45)),
                ('cantidad_partos', models.CharField(max_length=45)),
                ('fecha_ultimo_parto', models.DateField(verbose_name='Fecha de Ultimo Parto')),
                ('dias_lactancia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=45)),
                ('segundo_nombre', models.CharField(blank=True, max_length=45)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('segundo_apellido', models.CharField(blank=True, max_length=45)),
                ('cedula', models.IntegerField()),
                ('celular', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimento')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratacion')),
                ('sueldo', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=45)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produlect.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='empleado_login',
            fields=[
                ('id_empleado_login', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=45)),
                ('cedula', models.IntegerField()),
                ('cargo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_bovino',
            fields=[
                ('id_tipo_bovino', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_bovino', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='produccion',
            fields=[
                ('id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_produccion', models.DateField(verbose_name='Fecha de Produccion')),
                ('primera_produccion', models.DecimalField(decimal_places=3, max_digits=6)),
                ('segunda_produccion', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cantidad_concentrado', models.DecimalField(decimal_places=3, max_digits=6)),
                ('observaciones', models.TextField()),
                ('id_bovino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produlect.bovino')),
                ('id_empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produlect.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(max_length=45)),
                ('usuario', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produlect.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_tipo_bovino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produlect.tipo_bovino'),
        ),
    ]
