# Generated by Django 2.2.3 on 2019-08-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produlect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado_login',
            name='cargo',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
