# Generated by Django 2.2.3 on 2019-08-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produlect', '0002_auto_20190806_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='id_bovino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produlect.bovino'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produlect.empleado'),
        ),
    ]
