# Generated by Django 3.0.3 on 2020-02-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produlect', '0003_auto_20190806_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='codigo_produccion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_bovino',
            name='tipo_bovino',
            field=models.CharField(max_length=45),
        ),
    ]
