# Generated by Django 2.0.6 on 2020-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produlect', '0004_auto_20200217_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_bovino',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
